# Generated by Django 4.2.3 on 2023-09-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
