# Generated by Django 4.2.3 on 2023-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
    ]
