# Generated by Django 4.2.5 on 2023-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordercancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercancel',
            name='option',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordercancel',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
