# Generated by Django 4.2.3 on 2023-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
