# Generated by Django 4.2.5 on 2023-10-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_referraloffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralOffer',
        ),
    ]
