# Generated by Django 4.2.3 on 2023-09-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage_is_available'),
        ('cart', '0002_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productimage'),
        ),
    ]
