# Generated by Django 4.2.3 on 2023-09-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage_is_available'),
        ('cart', '0003_cart_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.productimage'),
            preserve_default=False,
        ),
    ]
