# Generated by Django 4.2.3 on 2023-10-18 02:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='single_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
