# Generated by Django 4.2.3 on 2023-10-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_single_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='single_total',
            field=models.IntegerField(),
        ),
    ]
