# Generated by Django 4.2.3 on 2023-09-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
    ]
