# Generated by Django 4.2.3 on 2023-09-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_address_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='userprofile'),
        ),
    ]
