# Generated by Django 4.2.3 on 2023-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_address_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile'),
        ),
    ]
