# Generated by Django 4.2.5 on 2023-10-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(choices=[('Cancel Order', 'Cancel Order'), ('Return Order', 'Return Order')], max_length=20, null=True),
        ),
    ]
