# Generated by Django 4.2.5 on 2023-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_transaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
