# Generated by Django 4.2.3 on 2023-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timme_st',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
