# Generated by Django 4.2.5 on 2023-10-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/userprofile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='refferal_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
