# Generated by Django 4.2.5 on 2023-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='discount_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
