# Generated by Django 4.2.3 on 2023-09-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
