# Generated by Django 4.2.3 on 2023-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
