# Generated by Django 4.2.5 on 2023-10-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_product_offer_offer_name'),
        ('product', '0007_productimage_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offer'),
        ),
    ]
