# Generated by Django 4.2.3 on 2023-09-25 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_address_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('messages', models.TextField()),
                ('tracking_no', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('od_status', models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Processing', 'Processing')], default='pending', max_length=150)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
