# Generated by Django 4.2.3 on 2023-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_created_at_alter_order_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='messages',
            field=models.TextField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Pending', 'Pending')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Pending', 'Pending')], default='pendings', max_length=150),
        ),
    ]
