# Generated by Django 4.2.3 on 2023-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_created_at_alter_order_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Return', 'Return'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Return', 'Return'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='pendings', max_length=150),
        ),
    ]
