# Generated by Django 4.2.3 on 2023-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_od_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Return', 'Return'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Return', 'Return'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='pendings', max_length=150),
        ),
    ]
