# Generated by Django 4.2.3 on 2023-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_alter_order_od_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Pending', 'Pending')], default='pending', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Pending', 'Pending')], default='pendings', max_length=150),
        ),
    ]
