# Generated by Django 4.2.3 on 2023-10-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0033_alter_order_od_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='pending', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='pendings', max_length=150),
        ),
    ]
